version: "3.9"

services: 
    # NGINX & PHP Server
    php-fpm:
        build:
            context: .
        ports: 
            - "8381:8080"
        volumes: 
            - wp-www:/var/www

volumes: 
    wp-www: